### ISSUE TITLE
import plots.gpkg failed

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#31]
Salut,
j'essaie de faire un import du fichier gpkg plots reproduit depuis mes données.

`niamoto import plots`

> ERROR:root:Error (DataValidationError): Missing required columns
> ✗ Error (DataValidationError): Missing required columns
> None

Voici ICI le [gpkg](https://www.dropbox.com/scl/fi/k4saw8f21gd3uz7cv9hnz/plots.gpkg?rlkey=a5nlj50q2rve5l0r8v63xhgrn&dl=0)

Voici le yml que j'utilise.
```
plots:
  type: vector
  format: geopackage
  path: "imports/plots.gpkg"
  identifier: "id_locality"
  location_field: "geometry"
```

Je suppose qu'il me manque une colonne mais laquelle ??
