### ISSUE TITLE
clarification transform.yml

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#32]
resalut,

j'essaie de bien comprendre la config du transform.yml. On distingue à chaque fois la table 'source' et la table 'reference'.

```
- group_by: taxon 
  identifier: id_taxonref
  source_table_name: occurrences
  source_location_field: geo_pt
  reference_table_name: full_name
```

`- group_by: taxon` 
## On indique ici sur quel type d'agrégation on travaille, ça renvoie à différentes fonctions py
` identifier: id_taxonref`
## Peut etre plus intuitif de nommer ici **reference_idenfier** ou **reference_link** ?
`source_table_name: occurrences`
## on croise les infos de la table taxon avec cette table, donc occurrences, logique
`source_location_field: geo_pt`
## logique
`reference_table_name: full_name`

**Comment by julienbarbe** [comment]
Salut Gilles,
@PhilippeBko @dimitri-justeau 

Merci pour tes remarques, et désolé pour le pavé, tu as ouvert une boîte de pandore :)
Je met tout le monde en copie, ça fait un petit point sur le dev en cours.

Oui tu as raison, "identifier" n'est pas très clair mais il y a une erreur dans ta configuration, reference_table_name devrait être taxon_ref, ça veut dire que les données brutes des occurrences et les calculs vont être agrégés autour des entrées de la table taxon_ref.

```yaml
- group_by: taxon
  identifier: id_taxonref
  source_table_name: occurrences
  source_location_field: geo_pt
  reference_table_name: taxon_ref
```

Pour être totalement explicite avec "identifier" il faudrait mettre source_reference_link peut-être.
Cette partie n'est pas satisfaisante, je suis en train de la revoir avec le système de plugin.

--- 

On aura toujours besoin de spécifier un identifiant quelque part, pour le reste l'idée est de gérer la source pour chaque transformation, dans ce style :

```yaml
dbh_distribution:
   plugin: binned_distribution
   data_source: occurrences # nom de la source dans import.yml
   source_field: dbh # nom du champ ou de l'attribut dans la source
   target_field: dbh_distribution # nom du champ résultat de la transformation
   params:
      bins: [10, 20, 30, 40]
      include_bounds: true
```

Parce que toutes les transformations n'ont pas forcément besoin de la même source de données, pour les plots par exemple on peut aller récupérer un attribut directement dans le geopackage, c'est pour ça qu'on peut aussi avoir une clé source pour dans les transformations, c'est pas clair, et les shapes c'est encore autre chose, je pense que la nouvelle version va clarifier tout ça. 

Pour te donner une idée on va avoir des plugins dédiées aux transformations et d'autres à l'export (widgets, html, api, publication), ça pourrait aussi être intéressant lors de l'import pour gérer des types de fichiers différents, configurer la hiérarchisation des référentiels, appeler des api directement, ça rend possible beaucoup de choses.
On pourra même chaîner les transformations si besoin. 

Je suis encore en phase de conception, les classes de base du système sont presque prêtes, j'ai une première liste de plugins pour donner une première idée des possibilités. 

### 1. Plugins de Transformation

#### 1.1 Collecteurs (collectors/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `field_aggregator` | Agrège des champs depuis différentes sources | - data_source<br>- source_field<br>- target_field |
| `direct_attribute` | Extrait une valeur directement | - data_source<br>- source_field<br>- target_field |
| `geospatial_extractor` | Extrait des géométries/coordonnées | - data_source<br>- source_field<br>- target_field<br>- params.format<br>- params.epsg |

#### 1.2 Analyseurs (analyzers/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `statistical_summary` | Calculs statistiques (min/max/mean...) | - data_source<br>- source_field<br>- target_field<br>- params.stats |
| `time_series_analysis` | Analyse temporelle (phénologie...) | - data_source<br>- source_field<br>- target_field<br>- params.metrics |

#### 1.3 Distributeurs (distributors/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `binary_distribution` | Distribution binaire | - data_source<br>- source_field<br>- target_field<br>- params.true_label<br>- params.false_label |
| `binned_distribution` | Distribution par intervalles | - data_source<br>- source_field<br>- target_field<br>- params.bins |

#### 1.4 Calculateurs (calculators/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `elevation_calculator` | Calcul de métriques d'élévation | - data_source<br>- source_field<br>- target_field<br>- params.stats |
| `area_calculator` | Calcul de surfaces | - data_source<br>- source_field<br>- target_field<br>- params.units |

### 2. Plugins d'Export

#### 2.1 Widgets (widgets/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `info_grid` | Affichage d'informations en grille | - title<br>- layout<br>- params.fields |
| `interactive_map` | Carte interactive | - title<br>- layout<br>- params.layers |
| `bar_plot` | Graphique en barres | - title<br>- params.datasets |
| `line_plot` | Graphique linéaire | - title<br>- params.datasets |
| `donut_chart` | Graphique circulaire | - title<br>- params.datasets |
| `gauge` | Jauge avec seuils | - title<br>- params.min<br>- params.max<br>- params.sectors |

#### 2.2 Générateurs (generators/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `page_generator` | Génère des pages HTML | - params.template<br>- params.depth |
| `api_generator` | Génère des endpoints JSON | - params.format<br>- params.fields |
| `tree_generator` | Génère des arbres de navigation | - params.template<br>- params.field_hierarchy |

#### 2.3 Publication (publishers/)

| Plugin | Description | Paramètres Requis |
|--------|-------------|------------------|
| `static_publisher` | Publication de fichiers statiques | - params.output_dir |
| `github_publisher` | Publication sur GitHub Pages | - params.repo<br>- params.branch |


Pour le chaînage des transformations ça pourrai donner quelque chose comme ça, ça permettrai d'envisager tous les calculs qu'on veut, si on veut les faire dans Niamoto, dans le cas contraire il suffira d'utiliser les plugins collectors (field_aggregator, direct_attribute directement des attributs d'un shape ou d'un plot)

```yaml
- group_by: shape
  transforms:
    forest_analysis:
      chain:
        # 1. Extraction de la géométrie
        - plugin: geospatial_extractor
          data_source: shapes.geometry
          target_field: shape_geom
          params:
            format: wkt
            epsg: 4326

        # 2. Intersection avec la couche forêt
        - plugin: layer_intersection
          source_field: shape_geom     # Utilise le résultat de l'étape 1
          data_source: layers.forest
          target_field: forest_area
          params:
            layer_field: geometry

        # 3. Calcul de surfaces
        - plugin: area_calculator
          source_field: forest_area    # Utilise le résultat de l'étape 2
          target_field: forest_surface
          params:
            units: hectares

        # 4. Distribution par altitude
        - plugin: elevation_distributor
          source_field: forest_area    # Utilise le résultat de l'étape 2
          data_source: layers.elevation
          target_field: elevation_dist
          params:
            bins: [100, 200, 300, 400]

        # 5. Calcul des statistiques finales
        - plugin: statistical_summary
          source_field: elevation_dist  # Utilise le résultat de l'étape 4
          target_field: elevation_stats
          params:
            stats: ["min", "mean", "max"]
```
