### ISSUE TITLE
data test Afrique centrale

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#36]
[occurrences.csv](https://github.com/user-attachments/files/19836441/occurrences.csv)
[plots.csv](https://github.com/user-attachments/files/19836442/plots.csv)

Salut @julienbarbe 

Voici un premier jeu de données plus ou moins 'minimaliste' pour tester le déploiement sur notre région.

Ci dessous le paramétrage de import.yml qui me semble correspondre aux jeux de données 

```
taxonomy:
  type: csv
  path: "imports/occurrences.csv"  # Chemin vers le fichier d'occurrences
  source: "occurrence"  # Indique d'extraire la taxonomie des occurrences
  ranks: "tax_fam,tax_gen,tax_sp_level,tax_infra_level"
  occurrence_columns:
    taxon_id: "idtax_n"
    family: "tax_fam"
    genus: "tax_gen"
    species: "tax_sp_level"
    infra: "tax_infra_level"
    authors: "tax_infra_level_auth"  # On peut extraire les auteurs du taxonref
```

```
occurrences:
  type: csv
  path: "imports/occurrences.csv"
  identifier: "idtax_n"
  location_field: "geo_pt"
```

```
plots:
  type: csv
  path: "imports/plots.csv"
  identifier: "id_liste_plots" #
  locality_field: "locality_name" #
  location_field: "geo_pt" # Champ de la géométrie de la localité
  link_field: "locality"  # **_Comprend pas ce qu'il faut mettre ici_**
  occurrence_link_field: "plot_name"  # Champ à utiliser dans occurrences pour le lien
```

Le lien entre plots et occurrences est donc si je comprends bien le champ indiqué dans 'occurrence_link_field'. 

```
shapes:
  - category: "country"
    type: vector
    format: directory_shapefiles
    path: "imports/shapes/countries"
    name_field: "CNTRY_NAME"
    label: "Country"
    description: "Administrative boundaries of the countries"
```

**_je ne comprend pas (plus) la nature de ces fichiers import_**
raw_plot_stats.csv
raw_shape_stats.csv

Aurais tu un exemple sur la base du shape fourni ?

[shapes.zip](https://github.com/user-attachments/files/19837385/shapes.zip)

**Comment by gdauby** [comment]
Ok, j'avais pas bien interprété le champ infra. Il est maintenant vide sauf s'il y a un niveau infra qui est alors mis dans la colonne infra avec le nom complet. OK ?
```
taxonomy:
  type: csv
  path: "imports/occurrences.csv"  # Chemin vers le fichier d'occurrences
  source: "occurrence"  # Indique d'extraire la taxonomie des occurrences
  ranks: "tax_fam,tax_gen,tax_sp_level,tax_infra_level"
  occurrence_columns:
    taxon_id: "idtax_n"
    family: "tax_fam"
    genus: "tax_gen"
    species: "tax_sp_level"
    infra: "tax_infra_level"
    authors: "tax_infra_level_auth"  # On peut extraire les auteurs du taxonref
```

Ok bon j'avais fait les choses trop vite la dernière et envoyé le mauvais csv

[raw_plot_stats.csv](https://github.com/user-attachments/files/19907228/raw_plot_stats.csv)
[row_shape_stats.csv](https://github.com/user-attachments/files/19907230/row_shape_stats.csv)
[plots.csv](https://github.com/user-attachments/files/19907229/plots.csv)
[occurrences.csv](https://github.com/user-attachments/files/19907231/occurrences.csv)

. 
Celui en attaché contient maintenant une colonne geo_pt en WKT
```
occurrences:
  type: csv
  path: "imports/occurrences.csv"
  identifier: "idtax_n"
  location_field: "geo_pt"
```

> Pour ta question sur les plots le link_field dans ton cas c’est aussi plot_name en fait puisque c’est le nom utilisé dans le champ plot_name des occurrences

Ok. Je me serai attendu de devoir aussi indiqué le yaml des occurrences ci dessus d'indiquer le nom du champ des plots.

```
plots:
  type: csv
  path: "imports/plots.csv"
  identifier: "id_liste_plots" #
  locality_field: "locality_name" #
  location_field: "geo_pt" # Champ de la géométrie de la localité
  link_field: "plot_name" 
  occurrence_link_field: "plot_name"  # Champ à utiliser dans occurrences pour le lien
```

Ok, j'ai compris maintenant les fichiers row_shape. Je crois qu'une des choses qui me perturbait c'était qu'il y avait un fichier shape alors qu'il y a (dans l'exemple de la Nlle Cal) beaucoup de shapes. En fait les entités unique des shapes  définis par le label de chaque label sont tous rassemblés dans le fichier row_shape. Pratique. N'y a t il pas un (petit) risque si une entité label a le même nom pour deux shape différents ?

Du coup, j'ai généré un row_shape_stats minimaliste pour les entités du shape country.
Et j'ai fait de même pour un row_plot_stats.

La config import devrait être la même que dans l'exemple

```
plot_stats:
  type: csv
  path: "imports/raw_plot_stats.csv"
  identifier: "plot_id"

shape_stats:
  type: csv
  path: "imports/row_shape_stats.csv"
  identifier: "id"
```



Pour le transform.yml ça devrait donner quelque chose comme ça (pour plots et shapes).

```
- group_by: plot
  source:
    data: plot_stats
    grouping: plot_ref
    relation:
      plugin: "stats_loader"
      key: "plot_id"

    map_panel:
      plugin: geospatial_extractor
      params:
        source: plots
        field: geo_pt
        format: geojson
      # ex: { "coordinates": [...], "label": ... }

   top_species:
      plugin: class_object_series_extractor
      params:
        source: plot_stats
        class_object: top10_species
        size_field:
          input: class_name
          output: tops
          numeric: false
          sort: false
        value_field:
          input: class_value
          output: counts
          numeric: true


    nbe_stem:
      plugin: direct_attribute
      params:
        source: plots
        field: nbe_stem
        format: number
        precision: 4 ### L'arrondi ???


- group_by: shape
  source:
    data: shape_stats
    grouping: shape_ref
    relation:
      plugin: "stats_loader"
      key: "id"

widgets_data:
plugin: class_object_field_aggregator
      params:
        fields:
          - source: shape_stats
            class_object: nbe_plot
            target: nbe_plots_country
            units: ""

```





[occurrences.csv](https://github.com/user-attachments/files/19907294/occurrences.csv)
[plots.csv](https://github.com/user-attachments/files/19907292/plots.csv)
[row_shape_stats.csv](https://github.com/user-attachments/files/19907293/row_shape_stats.csv)
[raw_plot_stats.csv](https://github.com/user-attachments/files/19907291/raw_plot_stats.csv)

**Comment by julienbarbe** [comment]
> N'y a t il pas un (petit) risque si une entité label a le même nom pour deux shape différents ?

Oui il y a un soucis ici, il faut que je trouve une solution


## La configuration donne ça 

### import.yml
```yaml
taxonomy:
  type: csv
  path: "imports/occurrences.csv"  # Chemin vers le fichier d'occurrences
  source: "occurrence"  # Indique d'extraire la taxonomie des occurrences
  ranks: "tax_fam,tax_gen,tax_sp_level,tax_infra_level"
  occurrence_columns:
    taxon_id: "idtax_n"
    family: "tax_fam"
    genus: "tax_gen"
    species: "tax_sp_level"
    infra: "tax_infra_level"
    authors: "tax_infra_level_auth"

plots:
  type: csv
  path: "imports/plots.csv"
  identifier: "id_liste_plots"
  locality_field: "plot_name"
  location_field: "geo_pt"
  link_field: "locality" 
  occurrence_link_field: "plot_name"


occurrences:
  type: csv
  path: "imports/occurrences.csv"
  identifier: "idtax_n"
  location_field: "geo_pt"

plot_stats:
  type: csv
  path: "imports/raw_plot_stats.csv"
  identifier: "plot_id"

shape_stats:
  type: csv
  path: "imports/raw_shape_stats.csv"
  identifier: "id"

shapes:
  - category: "country"
    type: vector
    format: geopackage
    path: "imports/shapes/countries.gpkg"
    name_field: "CNTRY_NAME"
    label: "Country"
    description: "Administrative boundaries of the countries"

```

### transform.yml
```yaml
##################################################################
# 1) CONFIG POUR LES TAXONS
##################################################################
- group_by: taxon
  source:
    data: occurrences
    grouping: taxon_ref
    relation:
      plugin: nested_set
      key: taxon_ref_id
      fields:
        parent: parent_id
        left: lft
        right: rght

  widgets_data:
    general_info:
      plugin: field_aggregator
      params:
        fields:
          - source: taxon_ref
            field: full_name
            target: name
          - source: taxon_ref
            field: rank_name
            target: rank
          - source: taxon_ref
            field: extra_data.taxon_type
            target: taxon_type
          - source: taxon_ref
            field: extra_data.parent_family
            target: parent_family
          - source: taxon_ref
            field: extra_data.parent_genus
            target: parent_genus
          - source: occurrences
            field: id
            target: occurrences_count
            transformation: count

    distribution_map:
      plugin: geospatial_extractor
      params:
        source: occurrences
        field: geo_pt
        format: geojson
        group_by_coordinates: true

    top_species:
      plugin: top_ranking
      params:
        source: occurrences
        field: taxon_ref_id
        target_ranks: ["tax_sp_level", "tax_infra_level"]
        count: 10

    wood_density:
      plugin: statistical_summary
      params:
        source: occurrences
        field: taxa_level_wood_density_mean
        stats: ["mean"]
        units: "g/cm3"
        max_value: 1.2

##################################################################
# 2) CONFIG POUR LES PLOTS
##################################################################
- group_by: plot
  source:
    data: plot_stats
    grouping: plot_ref
    relation:
      plugin: "stats_loader"
      key: "plot_id"

  widgets_data:
    general_info:
      plugin: field_aggregator
      params:
        fields:
          - source: plots
            field: locality_name
            target: plot_name
          - source: plots
            field: nbe_stem
            target: nbe_stem
            format: number

    map_panel:
      plugin: geospatial_extractor
      params:
        source: plots
        field: geo_pt
        format: geojson

    top_species:
      plugin: class_object_series_extractor
      params:
        source: plot_stats
        class_object: top10_species
        size_field:
          input: class_name
          output: tops
          numeric: false
          sort: false
        value_field:
          input: class_value
          output: counts
          numeric: true

##################################################################
# 3) CONFIG POUR LES SHAPES
##################################################################
- group_by: shape
  source:
    data: shape_stats
    grouping: shape_ref
    relation:
      plugin: "stats_loader"
      key: "id"

  widgets_data:
    general_info:
      plugin: class_object_field_aggregator
      params:
        fields:
          - source: shape_stats
            class_object: nbe_plot
            target: nbe_plots_country
            units: ""

    geography:
      plugin: shape_processor
      params:
        source: shape_ref
        field: location
        format: "topojson"
        simplify: true

```

### export.yml
```yaml
##################################################################
# 1) PRÉSENTATION POUR LES TAXONS
##################################################################
- group_by: taxon
  widgets:
    general_info:
      type: info_panel
      title: "Informations générales"
      layout: grid
      fields:
        - source: name
          label: Taxon
        - source: parent_family
          label: "Famille"
        - source: parent_genus
          label: "Genre"
        - source: rank
          label: "Rang"
          format: "map"
          mapping:
            "tax_fam": "Famille"
            "tax_gen": "Genre"
            "tax_sp_level": "Espèce"
            "tax_infra_level": "Sous-espèce"
        - source: occurrences_count
          label: "Nombre d'occurrences"
          format: "number"


    distribution_map:
      type: map_panel
      title: "Distribution géographique"
      description: Distribution géographique des occurrences du taxon et de ses sous-taxons
      source: distribution_map
      layout: full_width
      layers:
        - id: "occurrences"
          source: coordinates
          style:
            color: "#1fb99d"
            weight: 1
            fillColor: "#00716b"
            fillOpacity: 0.5
            radius: 2000

    top_species:
      type: bar_chart
      title: "Sous-taxons principaux"
      description: "Principaux sous-taxons (espèce, sous-espèce)"
      source: top_species
      sortData: true
      datasets:
        - label: 'Occurrences'
          data_key: counts
          generateColors: true 
      labels_key: tops
      options:
        indexAxis: 'y'
        scales:
          x:
            beginAtZero: true
            grid: {
              display: true,
              drawBorder: true,
              drawOnChartArea: true,
              drawTicks: true
            }
            ticks: {
              stepSize: 5
            }
            title:
              display: true
              text: "Nombre d'occurrences"
          y:
            grid: {
              display: false
            }
        plugins:
          legend: {
            display: false
          }
        maintainAspectRatio: false
        responsive: true

    wood_density:
      type: gauge
      title: "Densité de bois"
      description: Densité de bois moyenne mesuré avec une Tarière de Pressler
      source: wood_density
      value_key: "mean"
      options:
        min: 0
        max: 1.2
        units: "g/cm³"
        sectors:
          - color: '#f02828'
            range: [0.000, 0.240]
          - color: '#fe6a00'
            range: [0.240, 0.480]
          - color: '#e8dd0f'
            range: [0.480, 0.720]
          - color: '#81e042'
            range: [0.720, 0.960]
          - color: '#049f50'
            range: [0.960, 1.200]


##################################################################
# 2) PRÉSENTATION POUR LES PLOTS
##################################################################
- group_by: plot
  widgets:
    general_info:
      type: info_panel
      title: "Informations générales"
      layout: grid
      fields:
        - source: plot_name
          label: "Parcelle"
        - source: nbe_stem
          label: "Nombre de tiges"

    map_panel:
      type: map_panel
      title: "Localisation de la parcelle"
      source: map_panel
      layout: full_width
      layers:
        - id: "plot"
          source: geometry
          style:
            color: "#1fb99d"
            weight: 2
            fillOpacity: 0

    top_species:
      type: bar_chart
      title: "Sous-taxons principaux"
      description: "Les dix espèces botaniques les plus fréquentes de la parcelle"
      source: top_species
      sortData: true
      datasets:
        - label: 'Occurrences'
          data_key: counts
          generateColors: true 
      labels_key: tops
      options:
        indexAxis: 'y'
        scales:
          x:
            beginAtZero: true
            grid: {
              display: true,
              drawBorder: true,
              drawOnChartArea: true,
              drawTicks: true
            }
            ticks: {
              stepSize: 5
            }
            title:
              display: true
              text: "Nombre d'occurrences"
          y:
            grid: {
              display: false
            }
        plugins:
          legend: {
            display: false
          }
        maintainAspectRatio: false
        responsive: true

##################################################################
# 3) PRÉSENTATION POUR LES SHAPES
##################################################################
- group_by: shape
  widgets:
    general_info:
      type: info_panel
      title: "Informations générales"
      layout: grid
      fields:
        - source: nbe_plots_country
          label: "Nombre de parcelles"
          format: "number"

    map_panel:
      type: map_panel
      title: "Distribution de la forêt"
      description: "Distribution de la forêt dans l'emprise sélectionnée"
      source: geography
      layers:
        - id: shape
          source: geography.shape_coords
          style:
            color: "#1fb99d"
            weight: 2
            fillOpacity: 0
        - id: forest
          source: geography.forest_cover_coords
          style:
            color: "#228b22"
            weight: 0.3
            fillColor: "#228b22cc"
            fillOpacity: 0.8
```
