### ISSUE TITLE
export id from taxon_ref extra data

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#40]
Salut @julienbarbe 
Je fais un essai pour afficher une info de taxon_ref dans la colonne extra_data mais ça ne donne pas.
Voici les modifs que j'ai fait dans les yml

Dans transform.yml
```
widgets_data:
    general_info:
      plugin: field_aggregator
      params:
        fields:
          - source: taxon_ref
            field: full_name
            target: name
          - source: taxon_ref
            field: rank_name
            target: rank
          - source: taxon_ref
            field: extra_data.taxon_type
            target: taxon_type
          - source: taxon_ref
            field: extra_data.parent_family
            target: parent_family
          - source: taxon_ref
            field: extra_data.parent_genus
            target: parent_genus
          - source: occurrences
            field: id
            target: occurrences_count
            transformation: count
          - source: taxon_ref 
            field: extra_data.original_id ###  J'ai ajouté cette info
            target: original_id
```

Ensuite dans export.yml

```
display_fields:
            - name: "name"
              source: "general_info.name.value"
              fallback: "full_name"
              type: "text"
              label: "Scientific name"
              searchable: true
              
            - name: "rank"
              source: "general_info.rank.value"
              type: "select"
              label: "Taxonomic rank"
              format: "map"
              mapping:
                "tax_sp_level": "Espèce"
                "tax_infra_level": "Sous-espèce"
              filter_options:
                - {value: "tax_sp_level", label: "Species"}
                - {value: "tax_infra_level", label: "Infra species level"}
                
            - name: "parent_family"
              source: "general_info.parent_family.value"
              type: "select"
              label: "Family"
              dynamic_options: true
              
            - name: "parent_genus"
              source: "general_info.parent_genus.value"
              type: "text"
              label: "Genus"
              
            - name: "occurrences_count"
              source: "general_info.occurrences_count.value"
              type: "text"
              label: "Number of occurrences"
              format: "number"
                            
            - name: "original_id"
              source: "general_info.original_id.value"
              type: "text"
              label: "idtax"
              format: "number"
```
