### ISSUE TITLE
import shape

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#43]
J'ai une erreur lors de l'import du shape:

> ERROR:root:Error: Missing required fields (configuration key: shapes)
> ✗ Missing required fields (configuration key: shapes)
> ERROR:root:Error: Failed to import shapes
> ✗ Failed to import shapes
> ERROR:root:Error: Full import failed
> ✗ Full import failed
> Traceback (most recent call last):
>   File "C:\Users\dauby\AppData\Local\Programs\Python\Python312\Lib\site-packages\niamoto\core\services\importer.py", line 285,
> in import_shapes
>     return self.shape_importer.import_from_config(shapes_config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Initialement mon code d'import était 

```
shapes:
  - category: "country"
    type: vector
    format: directory_shapefiles
    path: "imports/shapes/central_africa"
    name_field: "name"
    label: "name_long"
    description: "Administrative boundaries of the countries"
```

Après j'ai vu sur la doc en ligne que ça avait changé et que ça devait ressembler à quelque chose comme ça:

```
shapes:
  - name: "country"
    type: shapefile
    path: "imports/shapes/central_africa/countries.shp"
    id_field: "id"
    name_field: "name"
```

Vois tu ou est mon erreur ?

Je vois qu'il y a maintenant un ajout possible :
```
    properties:
      - forest_type
      - canopy_cover
      - dominant_species
```
C'est pour remplacer le fichier initial **raw_shape_stats** ?

**Comment by julienbarbe** [comment]
C'est corrigé, la doc anticipe un peu parfois ;)

Mais le format est un peu différent tu peux essayer avec ça 
```yaml
 - type: "country"
   path: "imports/shapes/cameroon_gabon"
   name_field: "name"
   id_field: "id" # si les shapes viennent avec des id uniques
```

properties permet de récupérer des propriétés du shape, cela peut remplacer le raw_shape_stats pour les valeurs simples
