### ISSUE TITLE
error import plots.csv

### ISSUE THREAD

**Issue by gdauby** [niamoto/niamoto#44]
J'obtiens une erreur avec les fichiers en attaché et en faisant un import. Que fais je de pas bien ?

```
taxonomy:
  type: csv
  path: "imports/occurrences.csv"  # Chemin vers le fichier d'occurrences
  source: "occurrence"  # Indique d'extraire la taxonomie des occurrences
  ranks: "tax_fam,tax_gen,tax_sp_level,tax_infra_level"
  occurrence_columns:
    taxon_id: "idtax_individual_f"
    family: "tax_fam"
    genus: "tax_gen"
    species: "tax_sp_level"
    infra: "tax_infra_level"
    authors: "tax_infra_level_auth"

plots:
  type: csv
  path: "imports/plots.csv"
  identifier: "id_loc"
  locality_field: "locality_name"
  location_field: "geo_pt"
  link_field: "locality" 
  occurrence_link_field: "locality_name"
  hierarchy:
    enabled: true
    levels: ["locality_name", "country"]
    aggregate_geometry: true


occurrences:
  type: csv
  path: "imports/occurrences.csv"
  identifier: "idtax_individual_f"
  location_field: "geo_pt"

```

> ⠋ Importing plots...      ----------------------------------------   0% -:--:--
> ERROR:root:Error: Invalid geometry
> ✗ Invalid geometry
> ERROR:root:Error: Failed to import plots
> ✗ Failed to import plots
> ERROR:root:Error: Full import failed
> ✗ Full import failed
> Traceback (most recent call last):
>   File "C:\Users\dauby\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
>     self.dialect.do_execute(
>   File "C:\Users\dauby\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.IntegrityError: UNIQUE constraint failed: plot_ref.id

[occurrences.csv](https://github.com/user-attachments/files/20778140/occurrences.csv)
[plots.csv](https://github.com/user-attachments/files/20778141/plots.csv)
